config/routes.rb
Rails.application.routes.draw do
  get 'cards/show'
  get 'cards/history'
  get 'shops/show'
  resources :products
  get 'sessions/new'
  get 'users/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 
  # Defines the root path route ("/")
  # root "articles#index"
  get 'home/about'
 get "products/index"
 get "products/new"
 root"home#index"
 get "home/shop"
 get "home/signup"
 get "home/about"
 get "home/contact"
 get "home/testimal"
 get "/login", to: "sessions#new"
post "/login", to: "sessions#create"
delete "logout", to: "sessions#destroy"
delete "delete", to: "order_items#destroy"
 resources :stores
 resources :users
 resources :orders
 resources :shops, only:[:index, :show]
 resources :order_items
 resource :cards, only:[:show]
 get "stores/new"


end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @products = Product.all

    @order_item = current_order.order_items.new
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
    
end

app/views/shops/index.html.erb
<div class="container">
  <div class="row">
     <a><%= link_to"#{current_order.order_items.size} items add a value of#{current_order.subtotal}$",cards_path%></a>
    <% @products.each do |product| %>
      <div class="col-lg-2 col-md-6 mb-4">
           <%= link_to product, class: "card" do %>
          <%= image_tag(product.image, class: "card-img-top") if product.image.attached? %>
          <div class="card-body">
            <p class="card-text"><%= product.title %></p>
          </div>
          <div class="card-footer text-muted">
            <p class="card-text">Price: <%= product.price %></p>
          </div>
          <td>

        
          
        </td>
        <% end %>
        <%= form_for @order_item, remote: true  do |f|%>
          <%= f.hidden_field :product_id, :value => product.id %>
          <%= f.number_field :quantity, :value => 1, :min =>  1%>
          <%= f.submit "Add to Card "%>
          <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shops/show.html.erb
<h1>Shops#show</h1>
<p>Find me in app/views/shops/show.html.erb</p>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<%= link_to 'Back', root_path %>