config/routes.rb
Rails.application.routes.draw do
  get 'cards/show'
  get 'cards/history'
  get 'shops/show'
  resources :products
  get 'sessions/new'
  get 'users/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 
  # Defines the root path route ("/")
  # root "articles#index"
  get 'home/about'
 get "products/index"
 get "products/new"
 root"home#index"
 get "home/shop"
 get "home/signup"
 get "home/about"
 get "home/contact"
 get "home/testimal"
 get "/login", to: "sessions#new"
post "/login", to: "sessions#create"
delete "logout", to: "sessions#destroy"
delete "delete", to: "order_items#destroy"
 resources :stores
 resources :users
 resources :orders
 resources :shops, only:[:index, :show]
 resources :order_items
 resource :cards, only:[:show]
 get "stores/new"


end

app/models/store.rb
class Store < ApplicationRecord
    belongs_to :user
    has_many :products
   
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
    def index
        @stores = Store.all
    end

    def show 
        @store = Store.find_by(id: params[:id])
        @products = Product.all
        @users = User.all
    end

    def new
        @store = Store.new
    end

    def create
        @store = Store.new(store_params)
        @user = User.find_by(id: session[:user_id])
    
        @store.user_id = session[:user_id]
        if @store.save
            @user.update_attribute(:role, 1)
            @user.update_attribute(:store_id, current_user.id)
            
            flash[:success] = 'Create store successfully!'
            redirect_to root_path 
        else
            flash[:warning] = "Cannot create store!!"
            render :new
        end
        
        
    end

    def edit
        @store = Store.find(params[:id])
    end

    def update
        @store = Store.find(params[:id])
        if @store.update(store_params)
          
          flash[:success] = "Information updated"
          redirect_to @store
        else
        render 'edit'
        end
    end
    
    def destroy
        
    end
    def history
        @order = current_order 
    end
   

    private
        def store_params
            params.require(:store).permit(:name, :user_id, :description)
        end
end

app/helpers/stores_helper.rb
module StoresHelper
    def current_store
        @user = User.find_by(id: session[:user_id])
        if (@user && @user.role == 1)
            @user.store  
        else 
            return nil
        end
    end

    def create_store?
        !current_store.nil?
    end
end

app/views/stores/edit.html.erb
  <h1 class="title">Create Shop</h1>
        
        <%= form_with(model: @store, local: true)  do |form|  %>
        
            
        <div class="form-sign-up">
            <div class="mb-1 row">
                <label>Name store</label>
                 <%#= form.label :name %>
            </div>
            <div class="mb-3 row">
                <div class="col-sm-12">
                    <%= form.text_field :name, class: "form-control", placeholder: "name" %>
                </div>
            </div>
            <div class="mb-1 row">
                <%= form.label :description %>
            </div>
            <div class="mb-3 row">
                <div class="col-sm-12">
                    <%= form.text_field :description, class: "form-control", placeholder: "name@gmail.com" %>
                </div>
            </div>
            <div class="mb-1 row">
                <div class="col-sm-12">
                    <%= form.submit "Update store" , class: "btn btn-secondary max-width btn-border create-shop" %>
                </div>
            </div>
        </div>
        <% end %>

app/views/stores/new.html.erb
   
        <h1 class="title">Create Shop</h1>
        
        <%#= form_with model: @user, url: sign_up_path do |form| %>
        <%= form_with(model: @store, local: true)  do |form|  %>
        <%#= render 'shared/flash' %>
            
        <div class="form-sign-up">
            <div class="mb-1 row">
                <label>Name store</label>
                 <%#= form.label :name %>
            </div>
            <div class="mb-3 row">
                <div class="col-sm-12">
                    <%= form.text_field :name, class: "form-control", placeholder: "name" %>
                </div>
            </div>
            <div class="mb-1 row">
                <%= form.label :description %>
            </div>
            <div class="mb-3 row">
                <div class="col-sm-12">
                    <%= form.text_field :description, class: "form-control", placeholder: "name@gmail.com" %>
                </div>
            </div>
            <div class="mb-1 row">
                <div class="col-sm-12">
                    <%= form.submit "Create new store!" , class: "btn btn-secondary max-width btn-border create-shop" %>
                </div>
            </div>
        </div>
        <% end %>
   

app/views/stores/show.html.erb
 <section class="shop_section layout_padding">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
      
          
         <ul class="nav nav-tabs" id="myTab" role="tablist">
                                
                              <li class="nav-item">
                               Welcome to <%= @store.name %> shop <br/>
                               <%= @store.description %><br/>
                              <%= link_to "New products",products_new_path, class:"nav-link" %>
                                </li>
                            </ul>
     
        </h2>
      </div>
   
          
      <div class="row">
      <% @products.each do |product| %>
      <% if product.store_id == @store.id  %>
        <div class="col-sm-6 col-md-4 col-lg-3">
          <div class="box">
              <a href="">
              <div class="img-box">
              <%= image_tag(product.image, class: "card-img-top") if product.image.attached? %>
              </div>
              <div class="detail-box">
                <h6>
                  <%= product.title %>
                </h6>
                <h6>
                  Price
                  <span>
                    <%= product.price %>
                  </span>
                </h6>
              </div>
              <div class="new">
                <span>
                  <td><%= link_to 'More', product %></td>
                </span>
              </div>
            </a>
            <%= link_to "Update product", edit_product_path, class: "btn btn-info btn-lg btn-block" %> <br/>
          </div>
           
        </div>
        <% end %>
        <% end %>
      </div>
      
      
    </div>
    
    
  </section>
    