config/routes.rb
Rails.application.routes.draw do
  get 'cards/show'
  get 'cards/history'
  get 'shops/show'
  resources :products
  get 'sessions/new'
  get 'users/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 
  # Defines the root path route ("/")
  # root "articles#index"
  get 'home/about'
 get "products/index"
 get "products/new"
 root"home#index"
 get "home/shop"
 get "home/signup"
 get "home/about"
 get "home/contact"
 get "home/testimal"
 get "/login", to: "sessions#new"
post "/login", to: "sessions#create"
delete "logout", to: "sessions#destroy"
delete "delete", to: "order_items#destroy"
 resources :stores
 resources :users
 resources :orders
 resources :shops, only:[:index, :show]
 resources :order_items
 resource :cards, only:[:show]
 get "stores/new"


end

app/models/user.rb
class User < ApplicationRecord
  
    attr_accessor :remember_token
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: true
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    has_one_attached :avatar 
    has_one :store
    has_many :order_item
    has_one :order
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
    def forget
        update_attribute(:remember_digest, nil)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user, only: [:edit, :update]
  def index
    @users = User.all
    end   
  def show
    @user = User.find_by(id: params[:id])
  end
  def new
    @user = User.new
    end
def create
      @user = User.new(user_params)
      if @user.save
        log_in @user
        flash[:success] = "Welcome to the Sample App!"
        redirect_to @user
      # Handle a successful save.
      else
      render 'new', status: :unprocessable_entity
      end
      end
      

def destroy
        User.find(params[:id]).destroy
        redirect_to @@current_path
    end
    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
      end
def User.new_token
        SecureRandom.urlsafe_base64
        end
def edit
          @user = User.find(params[:id])
          end
def update
            @user = User.find(params[:id])
            if @user.update(user_params)
              
              flash[:success] = "Profile updated"
              redirect_to @user
            else
            render 'edit'
            end
end
def logged_in_user
  unless logged_in?
  flash[:danger] = "Please log in."
  redirect_to login_url
  end
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
    :password_confirmation,:avatar,:phone,:describe)
    end
def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
 
end
      

app/helpers/users_helper.rb
module UsersHelper
    # Returns the Gravatar for the given user.
    def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#
    {gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
    end

app/views/users/edit.html.erb
<div class="container">
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<div class="row">
<div class="col-md-6 col-md-offset-3">
<%= form_with(model: @user, local: true) do |f| %>

<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>
<%= f.label :email %>
<%= f.email_field :email, class: 'form-control' %>
<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>
<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation, class: 'form-control' %>
<%= f.label :phone, "Phone" %>
<%= f.text_field :phone, class: 'form-control' %>
<%= f.label :describe, "Describe" %>
<%= f.text_field :describe, class: 'form-control' %>
     
<div class="field">
<%= f.label :avatar, style: "display: block" %>
<%= f.file_field :avatar %>
</div>
<%= f.submit "Save changes", class: "btn btn-primary" %>
<% end %>

</div>
</div>
</div>
</div>

app/views/users/index.html.erb
 <div class="heading_container heading_center">
        <h2>
      
          
         <ul class="nav nav-tabs" id="myTab" role="tablist">
                                
                              <li class="nav-item">
                                    <h1>All users</h1>
                                </li>
                            </ul>
     
        </h2>
      </div>


<div class="row">
      <% @users.each do |user| %>
      
        <div class="col-sm-6 col-md-4 col-lg-3">
          <div class="box">
              
              <div class="img-box">
              <%= image_tag(user.avatar, class: "card-img-top") if user.avatar.attached? %>
              </div>
              <div class="detail-box">
                <h6>
                Name:
                <span>
                  <%= user.name %>
                  </span>
                </h6>
                <h6>
                  Phone:
                  <span>
                    0<%= user.phone %>
                  </span>
                </h6>
              </div>
              
           
          </div>
        </div>
        <% end %>
        
      </div>

app/views/users/new.html.erb
<div class="container">
 <div class="row" style="justify-content: center">
    <div class="col-md-6 col-md-offset-3">
    
    <%= form_with(model: @user) do |f| %>
    <%= render 'shared/error_messages' %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    <%= f.label :phone, "Phone" %>
    <%= f.text_field :phone, class: 'form-control' %>
    <%= f.label :describe, "Describe" %>
    <%= f.text_field :describe, class: 'form-control' %>
     
    <div class="field">
  <%= f.label :avatar, style: "display: block" %>
    <%= f.file_field :avatar %>
  </div>
    <%= f.submit "Create my account"
    %>
    <% end %>
    
    </div>
    </div>
    </div>

app/views/users/show.html.erb
<head>
      <style>body{
    background: -webkit-linear-gradient(#F9ECE6);
}
.emp-profile{
    padding: 3%;
    margin-top: 3%;
    margin-bottom: 3%;
    border-radius: 0.5rem;
    background: #F9ECE6;
}
.profile-img{
    text-align: center;
}
.profile-img img{
    width: 70%;
    height: 100%;
}
.profile-img .file {
    position: relative;
    overflow: hidden;
    margin-top: -20%;
    width: 70%;
    border: none;
    border-radius: 0;
    font-size: 15px;
    background: #212529b8;
}
.profile-img .file input {
    position: absolute;
    opacity: 0;
    right: 0;
    top: 0;
}
.profile-head h5{
    color: #333;
}
.profile-head h6{
    color: #0062cc;
}
.profile-edit-btn{
    border: none;
    border-radius: 1.5rem;
    width: 70%;
    padding: 2%;
    font-weight: 600;
    color: #6c757d;
    cursor: pointer;
}
.proile-rating{
    font-size: 12px;
    color: #818182;
    margin-top: 5%;
}
.proile-rating span{
    color: #495057;
    font-size: 15px;
    font-weight: 600;
}
.profile-head .nav-tabs{
    margin-bottom:5%;
}
.profile-head .nav-tabs .nav-link{
    font-weight:400;
    border: none;
}
.profile-head .nav-tabs .nav-link.active{
    border: none;
    border-bottom:2px solid #0062cc;
}
.profile-work{
    padding: 14%;
    margin-top: -15%;
}
.profile-work p{
    font-size: 12px;
    color: #818182;
    font-weight: 600;
    margin-top: 10%;
}
.profile-work a{
    text-decoration: none;
    color: #495057;
    font-weight: 600;
    font-size: 14px;
}
.profile-work ul{
    list-style: none;
}
.profile-tab label{
    font-weight: 600;
}
.profile-tab p{
    font-weight: 600;
    color: #0062cc;
}
 </style>
   </head>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container emp-profile">
            <form method="post">
                <div class="row">
                
                    <div class="col-md-4">
                        <div class="profile-img">
                              <%= image_tag(@user.avatar, class: "card-img-top") if @user.avatar.attached? %>
                            
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h5>
                                        <%= @user.name %>
                                    </h5>
                                    
                                    <p class="proile-rating">RANKINGS : <span>8/10</span></p>
                           
                        </div>
                    </div>
                    <div class="col-md-2">
                        
                        
                        <div class="profile-work">
                            
                                <br/>
                                <br/>
                                <br/>
                                 Work option<br/>
                                <%= link_to "Settings profile", edit_user_path(current_user), class:""%><br/>
                                <% if logged_in? %>
                                <% if create_store? %>
                                <%= link_to "Update store", edit_store_path, class: "" %> <br/>
                                <%= link_to "Store", store_path(current_store.id), class: "" %><br/>
                                <%= link_to "History order", cards_history_path, class: "" %> <br/>
                                <% else %>
                    
                                <%= link_to "Create store", new_store_path, class: "" %> <br/>
                                  
                                <% end %>
                               
                                <% end %>
                                 <%= link_to "All users", users_path %>
                              
                             
                             
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                       
                    </div>
                    <div class="col-md-8">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>User Id</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @user.name %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Name</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @user.name %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Email</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @user.email %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Phone</label>
                                                <p></p>
                                            </div>
                                            <div class="col-md-6">
                                                <p>0<%= @user.phone %></p>
                                            </div>
                                            
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Profession</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @user.describe %></p>
                                            </div>
                                        </div>
                            
                        </div>
                    </div>
                </div>
            </form>           
        </div>
<!--<%= @user.name %>, <%= @user.email %>
<% provide(:title, @user.name) %>
<div class="row">
<aside class="col-md-4">
<section class="user_info">
<h1>
<%= gravatar_for @user %>
<%= @user.name %>
</h1>
</section>
</aside>
</div>